### ISSUE TITLE
2018-03/Marzo-14 Entregable: Examen U1 y U2.

### ISSUE THREAD

**Issue by milkdoes** [milkdoes/kidsnao#11]
Desarrollar cada uno de los siguientes temas

* Sistemas basados en conocimiento
  * Concepto de conocimiento
  * Lenguajes utilizados en la representación de conocimiento.
* Mapas conceptuales.
* Redes semánticas.
* Lógica de predicados.
  * Sintaxis.
  * Semántica.
  * Validez.
  * Inferencia.
  * Ejemplos
* Razonamiento con incertidumbre.
  * Aprendizaje.
  * Razonamiento probabilístico
  * Lógicas multivaluadas.
  * Lógica difusa.
  * Ejemplos.
* Métodos.
* Problemas de búsqueda
  * Deterministicos
  * No deterministicos
  * Ejemplos

**Comment by milkdoes** [comment]
[Ex 1-2.pdf](https://github.com/milkdoes/kidsnao/files/1793018/Ex.1-2.pdf)

**Comment by jehovany2010** [comment]
a los métodos que se refiere?
