### ISSUE TITLE
Averiguar que tipo de madera se utiliza en la feria de proyectos.

### ISSUE THREAD

**Issue by milkdoes** [milkdoes/kidsnao#31]
Ni idea con quien se va para esto, pero suerte. :)

**Comment by CarlosVerde** [comment]
requieres de la madera tambien , que tan grande te parece apropiado ?

**Comment by milkdoes** [comment]
10 x 13 pulgadas esta bien.

**Comment by CarlosVerde** [comment]
enterado, en la semana te muestro lo que conseguí

**Comment by CarlosVerde** [comment]
la tabñla es rectangular de 11" por 22"
