### ISSUE TITLE
Conseguir/Comprar un mantel/superficie para permitir al NAO hacer sus coreografias.

### ISSUE THREAD

**Issue by milkdoes** [milkdoes/kidsnao#32]
Traerla a clase para probarla.

**Comment by 4dri4n** [comment]
Que caracteristicas debe de tener el mantel, es especial para nao o puede ser cualquiera?

**Comment by milkdoes** [comment]
Especial para el NAO.
Uno donde la superficie no sea dura para las caidas pero lo menos lisa para que no se resbale el NAO.

**Comment by milkdoes** [comment]
Tapete de 9 piezas conseguido.
Necesario pegar las frutas/verduras para no entrar en dificultad.
