### ISSUE TITLE
Encontrar canciones de disney junto con una coreografia bailable.

### ISSUE THREAD

**Issue by milkdoes** [milkdoes/kidsnao#33]
**Uno cada uno por lo minimo.**
Por favor canciones que les gusten y que piensen que les gustaran a los infantes.
Aparte que no tengan movimientos inseguros para ellos (incluyendo al NAO).

Escribir en un comentario los vinculos a la **coreografia (con personas bailando) y musica**.

|Cancion|Vinculo|Aceptada|Comentarios|
|---|---|---|---|
|Mover el bote, Madagascar|https://www.youtube.com/watch?v=Bzi7SGMN1zQ|Falta decidir.|No lo se, no lo puedes odiar ni amar.|
|Hakuna Matata|https://www.youtube.com/watch?v=WlDuk7fbfx4|No|Muy cringy.|
|Lo mas vital|https://youtu.be/-jUkteIUxvY|Falta decidir.|Me gusta mas por el hecho de las mujeres que la coreografia en si.|
|We're All In This Together|https://youtu.be/gbrbUfYSt0E?t=55s|No|Hay un espacio entre sin verguenza y sin dignidad.|
|Tarzan, Cuando estan destrosando el campamento los gorilas.|https://www.youtube.com/watch?v=ds42E6QjGRI|No.|Muy cringy.|
|Era de hielo 2, cuando hay muchos perezos cantando|https://www.youtube.com/watch?v=hWoTgzkGFU0|No|Mucho movimiento. No esta tan curada.|
|Aqui en nunca jamas , Peter Pan|https://www.youtube.com/watch?v=fOhqRW6-r5U|No|Muy cringy.|
|Let It Go - Frozen|https://www.youtube.com/watch?v=jV2L2SZWsnc|No|Ni loco.|
|Mickey Mouse Mash-Up arranged by John Higgins|https://www.youtube.com/watch?v=36mAEGUBB8s|No|Muy cringy.|
|Do You Want to Build a Snowman? (from Walt Disney Animation's FROZEN)|https://youtu.be/WXKmRoLloTE?t=46s|Si|Esta perfecta.|

**Comment by juliovillalobos14** [comment]
2 Canciones.
https://drive.google.com/drive/folders/1KIGSLqm0PyIc6IoE0AMDlluei4pO3_YS

**Comment by milkdoes** [comment]
Suenan bien, pero si no hay una coreografia bailada por otras personas, el que ponga las canciones las va a tener que bailar. Asi que, te puedes grabar un video contigo bailando las canciones o mejor utilizamos otras?

**Comment by juliovillalobos14** [comment]
Entiendo, entiendo, buscaré algo sobre eso, no creo animarme a bailarlas pero veré que puedo hacer.

**Comment by DEleanne** [comment]
Mover el bote, Madagascar
https://www.youtube.com/watch?v=Bzi7SGMN1zQ
Hakuna Matata
https://www.youtube.com/watch?v=WlDuk7fbfx4

**Comment by everdi** [comment]
https://youtu.be/-jUkteIUxvY
La canción es "lo mas vital" de la pelicula del libro de la selva, creo que es una buena canción.

busque canciones de Disney con coreografia pero son mas musicales y a mi parecer el baile es muy complejo para el NAO

**Comment by everdi** [comment]
https://youtu.be/gbrbUfYSt0E?t=55s

Creo que esta seria buena, nada mas la parte del coro, de hecho de donde inicia el link de arriba, son movimientos sencillos y es un buen mensaje ;)

**Comment by alonsoitt** [comment]
**- Tarzan, Cuando estan destrosando el campamento los gorilas.**

_https://www.youtube.com/watch?v=ds42E6QjGRI_

**- Era de hielo 2, cuando hay muchos perezos cantando**

_https://www.youtube.com/watch?v=hWoTgzkGFU0_

**Comment by miguelangelochoa** [comment]
Uca 2011
https://www.youtube.com/watch?v=kx1LMUxEfmo

**Comment by miguelangelochoa** [comment]
Aqui en nunca jamas , Peter Pan
https://www.youtube.com/watch?v=fOhqRW6-r5U

**Comment by miguelangelochoa** [comment]
Let It Go - Frozen
https://www.youtube.com/watch?v=jV2L2SZWsnc

**Comment by everdi** [comment]
https://www.youtube.com/watch?v=36mAEGUBB8s
Creo que esta estaria bien, es algo sencillo y repetitivo

https://youtu.be/WXKmRoLloTE?t=46s
Y este, solo el coro, desde el segundo 46
