### ISSUE TITLE
NAO: Coreografia de ¿Y si hacemos un muñeco? de Disney Frozen

### ISSUE THREAD

**Issue by milkdoes** [milkdoes/kidsnao#35]
Usar el vinculo para referencia de la coreografia:
https://youtu.be/WXKmRoLloTE?t=46s

Avisenme para descargar un remix particular (de youtube).

**Comment by ramirez-luis** [comment]
Ya lo subí, pero no estoy seguro si la canción se haya subido bien, o la coreografía...
