### ISSUE TITLE
Recomendar una cancion y una coreografia para cada tipo de genero musical listado.

### ISSUE THREAD

**Issue by milkdoes** [milkdoes/kidsnao#38]
Que la musica **no tenga groserias ni doble sentido**. Se usaran ambos para la feria de proyectos y para los infantes.
Evitar coreografias con mucho movimiento de pies y/o cambio de posiciones dentro del piso.

**NO REGGETON**. No se pasen de lanza.

Incluir:
* Nombre de la cancion.
* Vinculo de la cancion.
* Vinculo de la coreografia bailable.

| Cancion/Integrante | Alonso | Damaris | Evelin | Julio | Miguel |
| --- | --- | --- | ---| --- | --- |
| Punk ||||||
| Heavy Metal ||||||
| Pop ||||||
| Clasica ||||||
| Indie ||||||
| Folklorica ||||||
| Baile ||||||
| Jazz ||||||
| Rap ||||||

No editar dentro de la descripcion. Escribir en el comentario.

**Comment by DEleanne** [comment]
Espero que sirva :(
Punk
Musica
https://www.youtube.com/watch?v=OPf0YbXqDm0
Coreografía
https://youtu.be/n8QY1YmkQg4?t=1m36s
					
Heavy Metal
(este genero que ? cx jajaja, pues el heavy metal no se baila pero aqui esta un buen video de un niño y una cancion de para que lo acompañen)
Musica
https://www.youtube.com/watch?v=EsvHK4Bt1Y8
Coreografía
https://www.youtube.com/watch?v=T-CWY06UGe4
					
Pop
Musica
https://www.youtube.com/watch?v=ZbZSe6N_BXs
Coreografia
https://www.youtube.com/watch?v=jjkYHr94wnc

					
Clasica	
Musica
https://www.youtube.com/watch?v=CShopT9QUzw
https://www.youtube.com/watch?v=CShopT9QUzw
Coreografía
https://www.youtube.com/watch?v=hIvnpMCuO-I

				
Indie
Musica
https://www.youtube.com/watch?v=Pw-0pbY9JeU
Coreografía
https://www.youtube.com/watch?v=l9SgWflZyig
					
Folklorica
(enserio cx esta musica es muy complicada de bailar, lo que mas se mueve son los pies)
Musica
https://www.youtube.com/watch?v=edUxc_LaJ1E
Coreografía
https://www.youtube.com/watch?v=A_v8Ci9MAqo
										
Jazz	
Musica
https://www.youtube.com/watch?v=pUpAcPAipDA
Coreografía
https://www.youtube.com/watch?v=YMRXavy18ME
				
Rap
Musica
https://www.youtube.com/watch?v=a2v_zGWawP0
Coreografía
https://www.youtube.com/watch?v=Z_GeLQyPZog

**Comment by everdi** [comment]
1. Música     2. Baile

PUNK
1. https://www.youtube.com/watch?v=iymtpePP8I8
2. https://www.youtube.com/watch?v=N_hH6oGlKtg

HEAVY METAL
1. https://youtu.be/CSvFpBOe8eY
2. https://www.youtube.com/watch?v=379XZPyiUWM

POP
1. https://youtu.be/QJO3ROT-A4E
2.https://youtu.be/4WD01RMtloI

CLASICA
1.https://youtu.be/CYFUiYoYPbg
2.https://youtu.be/xPNjiJueZOw

INDIE
1.https://www.youtube.com/watch?v=Qiu3rvYveSg
2.https://www.youtube.com/watch?v=20onl-IX_y0

FOLKLORICA
1.https://youtu.be/y8aLkJ0SsBo 
2. https://youtu.be/la3bfPNCbUQ

BAILE
1.https://www.youtube.com/watch?v=YyG8fYBuRFM
2.https://www.youtube.com/watch?v=SrZhIuIDVf4

RAP
1. https://www.youtube.com/watch?v=_qQsPw4CqUI&feature=share
2. https://www.youtube.com/watch?v=9BvCPTvMjCw

JAZZ
1. https://www.youtube.com/watch?v=O-zpOMYRi0w
2.https://www.youtube.com/watch?v=GhcAV2XfwM0

PLUS https://www.youtube.com/watch?v=LySRrslj7l8

La mayoria de los generos son dificiles para el NAO, espero alguna funcione

**Comment by juliovillalobos14** [comment]
Punk

Canción: https://www.youtube.com/watch?time_continue=41&v=c1BOsShTyng
Coreografía: https://www.youtube.com/watch?v=7kD_IeWGjZo

Heavy Metal

Canción: https://www.youtube.com/watch?v=aSNJ00iAZ7I
Coreografía: https://www.youtube.com/watch?v=RKgWfVBVFi8

Pop

Canción: https://www.youtube.com/watch?v=ZEHsIcsjtdI
Coreografía: https://www.youtube.com/watch?v=2yK5pbUeIjE

Clasica

Canción: https://www.youtube.com/watch?v=__LU8E6dUsI
Coreografia: https://www.youtube.com/watch?v=uXFimc3DG7I

Indie

Canción: https://www.youtube.com/watch?time_continue=143&v=Ljg6g7BAdQo
Coreografia: https://www.youtube.com/watch?v=_kduqpSbTe0

Folklorica

Cancion: https://youtu.be/y8aLkJ0SsBo
Coreografia:  https://youtu.be/la3bfPNCbUQ

Baile

Canción: https://www.youtube.com/watch?v=T-Qnsk56_g4
Coreografia: https://www.youtube.com/watch?v=US2o6pwjwLk

Rap

Canción: https://www.youtube.com/watch?v=2zNSgSzhBfM
Coreografia: https://www.youtube.com/watch?v=JcbMSvAa-lQ

Jazz

Canción: https://www.youtube.com/watch?v=O-zpOMYRi0w
Coreografia: https://www.youtube.com/watch?v=GhcAV2XfwM0

**Comment by miguelangelochoa** [comment]
Punk
Musica
https://www.youtube.com/watch?v=h5EofwRzit0
Coreografía
https://www.youtube.com/watch?v=sS_QEGg3Ops

Heavy Metal
Musica
https://www.youtube.com/watch?v=CD-E-LDc384
Coreografía
https://www.youtube.com/watch?v=J7lsaq7GLmM

Pop
Musica
https://www.youtube.com/watch?v=kOkQ4T5WO9E
Coreografia
https://www.youtube.com/watch?v=vUlpNs7hzVE


Folklorica
Musica
https://www.youtube.com/watch?v=3sY-QdvBBdk
Coreografía
https://www.youtube.com/watch?v=hOkSvo8qBgI

Jazz
Musica
https://www.youtube.com/watch?v=QvluuW4n9qE
Coreografía
https://www.youtube.com/watch?v=FZbkO4iYZlQ

Rap   (La mas facil para mi xd)(puede ser cualquier rola)
Musica
https://www.youtube.com/watch?v=OPqS0Y5-2L4
Coreografía
https://www.youtube.com/watch?v=V3RTIzd6rm4

**Comment by alonsoitt** [comment]
Punk:

Canción: https://www.youtube.com/watch?v=9Ht5RZpzPqw
Coreografía: https://www.youtube.com/watch?v=WMzwwsGzwC4

Heavy Metal:

Canción: https://www.youtube.com/watch?v=L2VZjE6JdHg
Coreografía: https://www.youtube.com/watch?v=5NRsgeySmAU

Pop:

Canción: https://www.youtube.com/watch?v=UPNDK46QiRM
Coreografía: https://www.youtube.com/watch?v=zPAbD1Up-e4

Clásica:

Canción: https://www.youtube.com/watch?v=ZqQsShgJpgE
Coreografía: https://www.youtube.com/watch?v=zBIhQ9PcmsU

Indie:

Canción: https://www.youtube.com/watch?v=1G4isv_Fylg
Coreografía: https://www.youtube.com/watch?v=eYIRI1mWNKE

Folklorica:

Canción: https://www.youtube.com/watch?v=V-K2-5OfZVA
Coreografía: https://www.youtube.com/watch?v=Jre9veyoE9E

Jazz:

Canción: https://www.youtube.com/watch?v=RYJXX02KIZ0
Coreografía: https://www.youtube.com/watch?v=9BmLtbD2SUU

Rap:

Canción: https://www.youtube.com/watch?v=kn6-c223DUU
Coreografía: https://www.youtube.com/watch?v=4EVqR6BCZYA
